package com.ditchoom.webrtc.sctp

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * T0 floor for RFC 6525 RE-CONFIG: every parameter builds → encodes → decodes with its typed fields
 * intact and re-encodes byte-for-byte inside a real packet, the on-wire layouts are pinned against
 * the RFC's own field order (not just against our own encoder), and every malformed shape lands as a
 * typed reject rather than a throw, a null, or a fabricated value.
 *
 * The layout assertions matter more than usual here because the parameter bodies are generated by
 * buffer-codec from `@ProtocolMessage` field order: a reordered constructor would still round-trip
 * against itself perfectly while putting the wrong bytes on the wire. Only a fixed expected-byte
 * vector catches that, so each parameter has one.
 */
class ReConfigCodecTest {
    private val srcPort: UShort = 5000u
    private val dstPort: UShort = 5000u
    private val vtag = VerificationTag(0xDEADBEEFu)

    private fun packetOf(vararg chunks: SctpChunk): SctpPacket {
        val b = SctpPacketBuilder(srcPort, dstPort, vtag)
        for (c in chunks) b.add(c)
        return b.build()
    }

    // Encodes, decodes, asserts the checksum and a byte-exact re-encode, and returns the decoded chunk.
    private fun roundTripChunk(chunk: SctpChunk): SctpChunk.ReConfig {
        val enc = packetOf(chunk).encode()
        val original = enc.toIntList()
        enc.position(0)
        val decoded = assertIs<SctpDecodeResult.Success>(SctpPacket.decode(enc)).packet
        assertTrue(decoded.verifyChecksum(), "checksum must verify")
        assertEquals(original, decoded.encode().toIntList(), "decode→encode must be byte-exact")
        return assertIs<SctpChunk.ReConfig>(decoded.chunks.single())
    }

    private fun soleParameter(chunk: SctpChunk.ReConfig): ReConfigParameter =
        assertIs<ReConfigParameterDecode.Interpreted>(chunk.reConfigParameters().single()).parameter

    // The parameter's value bytes as they sit on the wire (padding excluded), as lowercase hex.
    private fun valueHex(parameter: ReConfigParameter): String = parameter.toParameter().value.toHex()

    // The parameter's value length in bytes, padding excluded.
    private fun valueSize(parameter: ReConfigParameter): Int = parameter.toParameter().value.remaining()

    @Test
    fun outgoingSsnResetRoundTripsWithStreams() {
        val original =
            ReConfigParameter.OutgoingSsnReset(
                requestSequenceNumber = ReConfigRequestSequenceNumber(0x11223344u),
                responseSequenceNumber = ReConfigRequestSequenceNumber(0x55667788u),
                senderLastAssignedTsn = Tsn(0x99AABBCCu),
                streams = listOf(StreamId(1), StreamId(0xFFFF)),
            )
        val decoded = soleParameter(roundTripChunk(SctpChunk.ReConfig.of(original)))
        assertEquals(original, decoded)
    }

    /**
     * RFC 6525 §4.1 layout: request seq, response seq, sender's last assigned TSN, then the stream ids
     * two bytes each. Pinned as bytes so a reordered `@ProtocolMessage` constructor cannot pass.
     */
    @Test
    fun outgoingSsnResetHasTheRfcFieldOrder() {
        val parameter =
            ReConfigParameter.OutgoingSsnReset(
                requestSequenceNumber = ReConfigRequestSequenceNumber(0x11223344u),
                responseSequenceNumber = ReConfigRequestSequenceNumber(0x55667788u),
                senderLastAssignedTsn = Tsn(0x99AABBCCu),
                streams = listOf(StreamId(0x0102), StreamId(0x0304)),
            )
        assertEquals(
            "11223344" + // request sequence number
                "55667788" + // response sequence number
                "99aabbcc" + // sender's last assigned TSN
                "0102" + "0304", // the two stream ids, 2 bytes each
            valueHex(parameter),
        )
    }

    /** An empty stream list means "every outgoing stream" (RFC 6525 §4.1) — 12 bytes, no trailer. */
    @Test
    fun outgoingSsnResetWithNoStreamsMeansAll() {
        val original =
            ReConfigParameter.OutgoingSsnReset(
                requestSequenceNumber = ReConfigRequestSequenceNumber(1u),
                responseSequenceNumber = ReConfigRequestSequenceNumber(2u),
                senderLastAssignedTsn = Tsn(3u),
                streams = emptyList(),
            )
        assertEquals(12, valueSize(original))
        val decoded = assertIs<ReConfigParameter.OutgoingSsnReset>(soleParameter(roundTripChunk(SctpChunk.ReConfig.of(original))))
        assertEquals(original, decoded)
        assertTrue(decoded.resetsAllStreams)
    }

    /**
     * An odd stream count makes the value 14 bytes, so the TLV needs two bytes of padding. The pad must
     * not be mistaken for a seventh stream id on the way back in — the decoder bounds the stream run by
     * the *declared* length, not by the padded region.
     */
    @Test
    fun outgoingSsnResetWithOddStreamCountSurvivesPadding() {
        val original =
            ReConfigParameter.OutgoingSsnReset(
                requestSequenceNumber = ReConfigRequestSequenceNumber(7u),
                responseSequenceNumber = ReConfigRequestSequenceNumber(8u),
                senderLastAssignedTsn = Tsn(9u),
                streams = listOf(StreamId(0x0A0B)),
            )
        val decoded = soleParameter(roundTripChunk(SctpChunk.ReConfig.of(original)))
        assertEquals(original, decoded)
        assertEquals(listOf(StreamId(0x0A0B)), (decoded as ReConfigParameter.OutgoingSsnReset).streams)
    }

    @Test
    fun incomingSsnResetRoundTrips() {
        val original =
            ReConfigParameter.IncomingSsnReset(
                requestSequenceNumber = ReConfigRequestSequenceNumber(0xCAFEBABEu),
                streams = listOf(StreamId(3), StreamId(5)),
            )
        assertEquals("cafebabe" + "0003" + "0005", valueHex(original))
        assertEquals(original, soleParameter(roundTripChunk(SctpChunk.ReConfig.of(original))))
    }

    @Test
    fun ssnTsnResetRoundTrips() {
        val original = ReConfigParameter.SsnTsnReset(ReConfigRequestSequenceNumber(0x01020304u))
        assertEquals("01020304", valueHex(original))
        assertEquals(original, soleParameter(roundTripChunk(SctpChunk.ReConfig.of(original))))
    }

    /** The 12-byte short form (RFC 6525 §4.4): response sequence + result, no TSN tail. */
    @Test
    fun responseShortFormRoundTrips() {
        val original =
            ReConfigParameter.Response(
                responseSequenceNumber = ReConfigRequestSequenceNumber(0x11112222u),
                result = ReConfigResult.SuccessPerformed,
            )
        assertEquals("11112222" + "00000001", valueHex(original))
        val decoded = assertIs<ReConfigParameter.Response>(soleParameter(roundTripChunk(SctpChunk.ReConfig.of(original))))
        assertEquals(original, decoded)
        assertNull(decoded.tsns, "the short form carries no TSNs")
        assertTrue(decoded.result.isSuccess)
    }

    /**
     * The 20-byte long form appends both TSNs. This is the generator's cascading-optional-trailer path
     * (`@When("remaining >= N")`); the short-form test above is the same codec taking the other branch,
     * so the pair pins that the tail is keyed off the declared length and nothing else.
     */
    @Test
    fun responseLongFormCarriesBothTsns() {
        val original =
            ReConfigParameter.Response(
                responseSequenceNumber = ReConfigRequestSequenceNumber(0xAAAABBBBu),
                result = ReConfigResult.InProgress,
                tsns = ReConfigParameter.TsnPair(Tsn(0x0000000Au), Tsn(0x0000000Bu)),
            )
        assertEquals(
            "aaaabbbb" + // response sequence number
                "00000006" + // result = InProgress
                "0000000a" + // sender's next TSN
                "0000000b", // receiver's next TSN
            valueHex(original),
        )
        val decoded = assertIs<ReConfigParameter.Response>(soleParameter(roundTripChunk(SctpChunk.ReConfig.of(original))))
        assertEquals(original, decoded)
        assertEquals(ReConfigParameter.TsnPair(Tsn(0x0000000Au), Tsn(0x0000000Bu)), decoded.tsns)
    }

    @Test
    fun everyResultValueRoundTrips() {
        for (result in ReConfigResult.entries) {
            val original = ReConfigParameter.Response(ReConfigRequestSequenceNumber(1u), result)
            val decoded = assertIs<ReConfigParameter.Response>(soleParameter(roundTripChunk(SctpChunk.ReConfig.of(original))))
            assertEquals(result, decoded.result, "result $result must survive the round trip")
            assertEquals(
                result.wireValue.toString(16).padStart(8, '0'),
                valueHex(original).substring(8),
                "result must ride as its assigned value",
            )
        }
    }

    @Test
    fun addStreamsRequestsRoundTripAndStayDistinct() {
        val outgoing = ReConfigParameter.AddOutgoingStreams(ReConfigRequestSequenceNumber(0x01020304u), 6u)
        val incoming = ReConfigParameter.AddIncomingStreams(ReConfigRequestSequenceNumber(0x01020304u), 6u)
        // Same body, different parameter type — the type is what tells them apart.
        assertEquals("01020304" + "0006" + "0000", valueHex(outgoing))
        assertEquals(valueHex(outgoing), valueHex(incoming))
        assertEquals(outgoing, soleParameter(roundTripChunk(SctpChunk.ReConfig.of(outgoing))))
        assertEquals(incoming, soleParameter(roundTripChunk(SctpChunk.ReConfig.of(incoming))))
    }

    /** RFC 6525 §3.1 allows a request and a response bundled in one chunk — the common close pattern. */
    @Test
    fun twoParameterChunkRoundTrips() {
        val request =
            ReConfigParameter.OutgoingSsnReset(
                requestSequenceNumber = ReConfigRequestSequenceNumber(1u),
                responseSequenceNumber = ReConfigRequestSequenceNumber(0u),
                senderLastAssignedTsn = Tsn(100u),
                streams = listOf(StreamId(2)),
            )
        val response = ReConfigParameter.Response(ReConfigRequestSequenceNumber(9u), ReConfigResult.SuccessPerformed)
        val chunk = roundTripChunk(SctpChunk.ReConfig.of(request, response))
        assertTrue(chunk.wellFormed, "one request + one response is the RFC 6525 §3.1 shape")
        val decoded = chunk.reConfigParameters().map { assertIs<ReConfigParameterDecode.Interpreted>(it).parameter }
        assertEquals(listOf<ReConfigParameter>(request, response), decoded)
    }

    @Test
    fun chunkWithThreeParametersIsNotWellFormedButStillReEncodes() {
        val response = ReConfigParameter.Response(ReConfigRequestSequenceNumber(1u), ReConfigResult.Denied)
        val chunk = roundTripChunk(SctpChunk.ReConfig.of(response, response, response))
        assertTrue(!chunk.wellFormed, "RFC 6525 §3.1 caps a RE-CONFIG at two parameters")
        assertEquals(3, chunk.parameters.size, "the chunk is still preserved verbatim")
    }

    // ── typed rejects: every malformed shape is data, never a throw and never a silent default ──

    private fun decodeOf(
        type: ParameterType,
        vararg valueBytes: Int,
    ): ReConfigParameterDecode = SctpParameter.ofValue(type, bufferOf(*valueBytes)).asReConfigParameter()

    @Test
    fun truncatedOutgoingResetIsTypedMalformed() {
        val reject = assertIs<ReConfigParameterDecode.Malformed>(decodeOf(ParameterType.OutgoingSsnResetRequest, 1, 2, 3, 4))
        assertEquals(ParameterType.OutgoingSsnResetRequest, reject.type)
        assertEquals(ReConfigMalformedReason.WrongLength(4), reject.reason)
    }

    @Test
    fun raggedStreamListIsTypedMalformed() {
        // 12 fixed bytes + 1 trailing byte: not a whole number of 2-byte stream ids.
        val reject =
            assertIs<ReConfigParameterDecode.Malformed>(
                decodeOf(ParameterType.OutgoingSsnResetRequest, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0xFF),
            )
        assertEquals(ReConfigMalformedReason.RaggedStreamList(1), reject.reason)
    }

    @Test
    fun unassignedResultIsTypedMalformed() {
        // Result 99 is not an RFC 6525 §4.4 assigned value — it must not decode to a fabricated variant.
        val reject =
            assertIs<ReConfigParameterDecode.Malformed>(
                decodeOf(ParameterType.ReConfigResponse, 0, 0, 0, 1, 0, 0, 0, 99),
            )
        assertEquals(ReConfigMalformedReason.UnassignedResult(99u), reject.reason)
    }

    @Test
    fun responseOfInBetweenLengthIsTypedMalformed() {
        // 12 bytes: neither the 8-byte short body nor the 16-byte long one.
        val reject =
            assertIs<ReConfigParameterDecode.Malformed>(
                decodeOf(ParameterType.ReConfigResponse, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 5),
            )
        assertEquals(ReConfigMalformedReason.WrongLength(12), reject.reason)
    }

    @Test
    fun wrongSizedFixedParametersAreTypedMalformed() {
        assertIs<ReConfigParameterDecode.Malformed>(decodeOf(ParameterType.SsnTsnResetRequest, 1, 2, 3))
        assertIs<ReConfigParameterDecode.Malformed>(decodeOf(ParameterType.AddOutgoingStreamsRequest, 1, 2, 3, 4))
        assertIs<ReConfigParameterDecode.Malformed>(decodeOf(ParameterType.AddIncomingStreamsRequest, 1, 2, 3, 4, 5))
    }

    /** A non-RE-CONFIG parameter is *not* an error — it is simply not ours, and says so distinctly. */
    @Test
    fun nonReConfigParameterIsDistinctFromMalformed() {
        assertEquals(ReConfigParameterDecode.NotReConfig, SctpParameter.forwardTsnSupported().asReConfigParameter())
        assertEquals(ReConfigParameterDecode.NotReConfig, decodeOf(ParameterType.StateCookie, 1, 2, 3, 4))
    }

    /** RE-CONFIG's high bits are `10`: a peer without RFC 6525 skips the chunk and keeps parsing. */
    @Test
    fun reConfigChunkTypeIsSkipAndContinue() {
        assertEquals(130u.toUByte(), SctpChunkType.ReConfig.value)
        assertEquals(UnrecognizedAction.SkipAndContinue, SctpChunkType.ReConfig.unrecognizedAction)
    }

    /**
     * **Golden vector** — these bytes, and their CRC32c, were produced by an encoder written
     * independently of this one (the generator for the `reconfig-outgoing-reset-response.bin` Jazzer
     * seed, which lays the fields out straight from RFC 6525 §3.1/§4.1/§4.4). Decoding them is
     * therefore a differential check rather than a self-consistency one: every test above could pass
     * against a codec that is uniformly wrong, this one could not.
     *
     * Layout: a RE-CONFIG chunk (type 130) carrying an Outgoing SSN Reset Request for stream 3 and a
     * long-form Re-configuration Response — the bundled request+response shape RFC 6525 §3.1 describes.
     */
    @Test
    fun decodesAnIndependentlyEncodedGoldenVector() {
        val wire =
            bufferOfHex(
                "13881388deadbeef94b7e9a8" + // src 5000, dst 5000, vtag 0xDEADBEEF, CRC32c (LE)
                    "8200002c" + // chunk: type 130, flags 0, length 44
                    "000d0012112233445566778899aabbcc00030000" + // outgoing reset + pad
                    "0010001455667788000000010000000a0000000b", // response, long form
            )
        val packet = assertIs<SctpDecodeResult.Success>(SctpPacket.decode(wire)).packet
        assertTrue(packet.verifyChecksum(), "the externally computed CRC32c must verify")

        val chunk = assertIs<SctpChunk.ReConfig>(packet.chunks.single())
        assertTrue(chunk.wellFormed)
        val parameters = chunk.reConfigParameters().map { assertIs<ReConfigParameterDecode.Interpreted>(it).parameter }

        assertEquals(
            ReConfigParameter.OutgoingSsnReset(
                requestSequenceNumber = ReConfigRequestSequenceNumber(0x11223344u),
                responseSequenceNumber = ReConfigRequestSequenceNumber(0x55667788u),
                senderLastAssignedTsn = Tsn(0x99AABBCCu),
                streams = listOf(StreamId(3)),
            ),
            parameters[0],
        )
        assertEquals(
            ReConfigParameter.Response(
                responseSequenceNumber = ReConfigRequestSequenceNumber(0x55667788u),
                result = ReConfigResult.SuccessPerformed,
                tsns = ReConfigParameter.TsnPair(Tsn(0x0000000Au), Tsn(0x0000000Bu)),
            ),
            parameters[1],
        )
    }
}
